/*
 * generated by Xtext
 */
package rs.demsys.rst.ui.contentassist

import rs.demsys.rst.ui.contentassist.AbstractBibProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BibProposalProvider extends AbstractBibProposalProvider {
}
