/*
 * generated by Xtext
 */
package rs.demsys.rst;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RstRuntimeModule extends rs.demsys.rst.AbstractRstRuntimeModule {

}
