/*
 * generated by Xtext
 */
package rs.demsys.rst;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RstStandaloneSetup extends RstStandaloneSetupGenerated{

	public static void doSetup() {
		new RstStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

